### ISSUE TITLE
Research if we do automatic GPS position well enough and whether there are ways to improve

### ISSUE THREAD

**Issue by mpinter** [bratislava/enforcement-scan-app-native#83]
We have reports that previously, on the same devices, the automatic GPS was better than it is today. We shoudl verify if we can request the GPS position more aggressively from the system before we send it to backend, or whether we're not sending incorrect GPS because of other reasons.

Related to the task of reporting whether the GPS was manually edited or automatic.

**Comment by vidriduch** [comment]
Closing as this was investigated and addressed in multiple PRs, for instance, #107
